services:

  https-portal:
    restart: unless-stopped

  mariadb:
    restart: unless-stopped

  nginx:
    restart: unless-stopped

  php:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped

  redis:
    restart: unless-stopped
